// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKATtmRX7p3Yn3WiNEY6o7wQM1L6HGN8',
    appId: '1:700651288099:web:5e70f92f5808587e73e396',
    messagingSenderId: '700651288099',
    projectId: 'wordwhizz-24087',
    authDomain: 'wordwhizz-24087.firebaseapp.com',
    storageBucket: 'wordwhizz-24087.firebasestorage.app',
    measurementId: 'G-FERL7CFMCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25X8FOMD3LeZxdvvuciP0TP7Q1j8lp4s',
    appId: '1:700651288099:android:f25a8dda01052d5873e396',
    messagingSenderId: '700651288099',
    projectId: 'wordwhizz-24087',
    storageBucket: 'wordwhizz-24087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9KoSmJj7tStElKCVOvWQvC3Ky7LPt2Gc',
    appId: '1:700651288099:ios:60de49ecd9e1275d73e396',
    messagingSenderId: '700651288099',
    projectId: 'wordwhizz-24087',
    storageBucket: 'wordwhizz-24087.firebasestorage.app',
    iosBundleId: 'com.example.wordwhizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9KoSmJj7tStElKCVOvWQvC3Ky7LPt2Gc',
    appId: '1:700651288099:ios:60de49ecd9e1275d73e396',
    messagingSenderId: '700651288099',
    projectId: 'wordwhizz-24087',
    storageBucket: 'wordwhizz-24087.firebasestorage.app',
    iosBundleId: 'com.example.wordwhizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKATtmRX7p3Yn3WiNEY6o7wQM1L6HGN8',
    appId: '1:700651288099:web:6b5af7ff4af6625c73e396',
    messagingSenderId: '700651288099',
    projectId: 'wordwhizz-24087',
    authDomain: 'wordwhizz-24087.firebaseapp.com',
    storageBucket: 'wordwhizz-24087.firebasestorage.app',
    measurementId: 'G-03F02X6T9V',
  );
}
